<?php

namespace SW\DocManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    
    public function getMainCategories() {
        
        $queryBuilder = $this->createQueryBuilder('c');        
        $queryBuilder->where('c.main = true');
        
        return $queryBuilder
                ->getQuery()
                ->getResult();
    }
    
    /**
     * SELECT DISTINCT t1.name
            FROM category t1
            LEFT JOIN category t2 ON t2.parent_id = t1.id
            WHERE t2.id IS NULL
     * 
     * @return ArrayCollection
     */
    public function getSubSubCategories() {          
                
          $qb = $this->_em
                  ->createQuery('SELECT t1
            FROM SWDocManagerBundle:Category t1
            LEFT JOIN SWDocManagerBundle:Category t2 WITH t2.parent = t1.id
            WHERE t2.id IS NULL AND t1.main = false');
        
        return $qb
                ->getResult();
        
    }  
    
    public function getSubCategories() {
        
        $parents = $this->getMainCategories();
        
        $queryBuilder = $this->createQueryBuilder('c');   
        $queryBuilder->andWhere('c.parent IN (:ids)')
                ->select('c.name')
                ->distinct()
                ->setParameter('ids', $parents);
        
        return $queryBuilder
                ->getQuery()
                ->getResult();
        
    }
    
    public function getCode($id) {
        
        $queryBuilder = $this->createQueryBuilder('c');        
        $queryBuilder
                ->select('c.code')
                ->where('c.id = :id')
                ->setParameter('id', $id);
        
        $array = $queryBuilder
                ->getQuery()
                ->getOneOrNullResult();
        
        return sizeof($array) > 0 ? $array['code'] : '';
        
    }
}
