<?php

namespace SW\DocManagerBundle\Entity;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{
    const LIMIT_SEARCH = 10;


    public function getByCode($code) {
        $queryBuilder = $this->createQueryBuilder('d');    
        
        $queryBuilder
                ->where('d.code LIKE :code')
                ->andWhere('d.disabled = 1')
                ->setParameter('code', '%' . $code . '%')
                ->setMaxResults(self::LIMIT_SEARCH)
                ->getQuery();
        
        return $queryBuilder
                ->getQuery()
                ->getResult();
    }
    
    public function getOneByName($name) {
        $queryBuilder = $this->createQueryBuilder('d');    
        
        $queryBuilder
                ->where('d.name = :name')
                ->andWhere('d.disabled = 1')
                ->setParameter('name', $name)
                ->getQuery();
        
        return $queryBuilder
                ->getQuery()
                ->getOneOrNullResult();
    }
}
