<?php

namespace SW\DocManagerBundle\Entity;

/**
 * tFormatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormatRepository extends \Doctrine\ORM\EntityRepository
{
}
