<?php

namespace SW\DocManagerBundle\Entity;

/**
 * UploadSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadSessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDocumentName($document)
    {
        return $this->createQueryBuilder('u')
                ->innerJoin('u.documents', 'd', 'WITH', 'd.name = :superCategoryName')
                ->setParameter('superCategoryName', $document->getName());
    }
}