sw_doc_manager_homepage:
    path:     /hello/{name}
    defaults: { _controller: SWDocManagerBundle:Default:index }
    
sw_doc_manager_add:
    path:     /add/{status}
    defaults: 
        _controller: SWDocManagerBundle:Add:categoryList
        status:
    requirements:
        status: (success|failed)?
       
sw_doc_manager_publish:
    path:     /publish
    defaults: { _controller: SWDocManagerBundle:Add:publish }
    