sw_doc_manager_homepage:
    path:     /
    defaults: { _controller: SWDocManagerBundle:Default:index }
    
sw_doc_manager_add:
    path:     /add/{status}
    defaults: 
        _controller: SWDocManagerBundle:Add:categoryList
        status:
    requirements:
        status: (success|failed)?
        
sw_doc_manager_upload:
    path:     /add/{id}
    defaults: 
        _controller: SWDocManagerBundle:Add:uploadView       
     
sw_doc_manager_recap:
    path:     /recap/{id}
    defaults: 
        _controller: SWDocManagerBundle:Add:recap
    requirements: 
        id: \d+
        
sw_doc_manager_publish:
    path:     /publish
    defaults: { _controller: SWDocManagerBundle:Add:publish }
    
sw_doc_manager_list_ajax:
    path:   /list
    defaults: { _controller: SWDocManagerBundle:View:list }
    
sw_doc_manager_view:
    path:   /view/{id}
    defaults: { _controller: SWDocManagerBundle:View:render }
    
sw_doc_manager_edit_post:
    path: /edit/{force}
    defaults: { _controller: SWDocManagerBundle:Edit:edit }
    requirements:
        force: true|false
        
sw_doc_manager_delete:
    path: /delete
    defaults: { _controller: SWDocManagerBundle:Delete:delete }
    requirements:
        method:   POST