sw_doc_manager_homepage:
    path:     /hello/{name}
    defaults: { _controller: SWDocManagerBundle:Default:index }
    
sw_doc_manager_add:
    path:     /add
    defaults: { _controller: SWDocManagerBundle:Add:categoryList }
       
sw_doc_manager_publish:
    path:     /publish
    defaults: { _controller: SWDocManagerBundle:Add:publish }
    