services:
#    sw_doc_manager.example:
#        class: SW\DocManagerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    sw_doc_manager.date_service:
        class: SW\DocManagerBundle\Services\DateService